### ISSUE TITLE
🐛 SDK spinner is not working from WSL

### ISSUE THREAD

**Issue by mariocao** [sedaprotocol/seda-sdk#107]
#### Stack trace & error message

While deploying an oracle program from WSL ubuntu, this error happens:

```
117468 |   if (!writableStream.isTTY) {
117469 |     return;
117470 |   }
117471 |   restore_cursor_default();
117472 |   isHidden = true;
117473 |   writableStream.write("\x1B[?25l");
         ^
EPERM: Operation not permitted
   errno: -1
 syscall: "write"
      fd: 16

      at write (native:1:1)
      at NativeWritablePrototypeWrite (node:stream:3671:38)
      at /home/amazon/hackathon/chain-abstraction/seda-request-starter-kit/node_modules/@seda-protocol/dev-tools/bin/index.js:117473:18
      at start (/home/amazon/hackathon/chain-abstraction/seda-request-starter-kit/node_modules/@seda-protocol/dev-tools/bin/index.js:117888:26)
      at updateSpinnerText (/home/amazon/hackathon/chain-abstraction/seda-request-starter-kit/node_modules/@seda-protocol/dev-tools/bin/index.js:117957:11)
      at /home/amazon/hackathon/chain-abstraction/seda-request-starter-kit/node_modules/@seda-protocol/dev-tools/bin/index.js:123827:3
      at processTicksAndRejections (native:7:39)

Bun v1.1.34 (Linux x64)
error: "seda-sdk" exited with code 1
```

## Your Environment

- Windows + WSL ubuntu

**Comment by gluax** [comment]
I can test this since I do development in WSL.

**Comment by gluax** [comment]
I cannot replicate this bug, at least with the main branch of the repo.

**Comment by mariocao** [comment]
@Thomasvdam asked and we are waiting for response.

**Comment by Thomasvdam** [comment]
Given that we haven't heard anything we'll close this. If it pops up again we can reopen this issue or open a new one.
